### ISSUE TITLE
Could the HAML dependency be made optional?

### ISSUE THREAD

**Issue by bendiken** [gkellogg/ebnf#4]
I was wondering why my project was pulling in the HAML stack (a bit of a WTF moment),  and eventually figured out that it's being pulled in transitively through `rdf-turtle` to `ebnf`. It does seem perhaps a tad heavy-handed to pull in HAML to just parse Turtle--any chance of making that a development dependency instead of a runtime one?

**Comment by gkellogg** [comment]
It seems to be in there for outputting the EBNF as HTML, which can be useful. But, it certainly should be a soft dependency. I'll get an update out.

**Comment by gkellogg** [comment]
Pushed out in 0.3.9.

**Comment by bendiken** [comment]
Thanks, Gregg!
